ToDoListApp/Controllers/ToDoesController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Helpers;
using System.Web.Mvc;
using ToDoListApp.Models;

namespace ToDoListApp.Controllers
{
    [System.Runtime.InteropServices.Guid("BDF27A89-253C-41C6-9D87-A8178B0B6191")]
    public class ToDoesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ToDoes
        public ActionResult Index()
        {
            SendEmail();

            return View();

        }
        private IEnumerable<ToDo> GetListOfToDo()
        {
            string currentUserId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.FirstOrDefault(x => x.Id == currentUserId);
            return db.toDos.ToList().Where(x => x.user == currentUser).OrderByDescending(x => x.id);
        }
        public ActionResult DyanmicTable()
        {
            return PartialView("_TodoAjaxTable", GetListOfToDo());
        }
        // GET: ToDoes/Details/5
        public ActionResult Details(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDo toDo = db.toDos.Find(id);
            if(toDo == null)
            {
                return HttpNotFound();
            }
            return View(toDo);
        }

        // GET: ToDoes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ToDoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,title,description,reminder,isDone")] ToDo toDo)
        {
            if(ModelState.IsValid)
            {
                if(toDo.reminder == null)
                {

                    toDo.reminder = DateTime.Now;
                }

                string currentUserId = User.Identity.GetUserId();
                ApplicationUser currentUser = db.Users.FirstOrDefault(x => x.Id == currentUserId);
                toDo.user = currentUser;
                db.toDos.Add(toDo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(toDo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateAjaxForm([Bind(Include = "id,title,description,reminder")] ToDo toDo)
        {
            if(ModelState.IsValid)
            {
                if(toDo.reminder == null)
                {

                    toDo.reminder = DateTime.Now;
                }

                string currentUserId = User.Identity.GetUserId();
                ApplicationUser currentUser = db.Users.FirstOrDefault(x => x.Id == currentUserId);
                toDo.user = currentUser;
                toDo.isDone = false;
                db.toDos.Add(toDo);
                db.SaveChanges();
                //return RedirectToAction("Index");
            }

            return PartialView("_TodoAjaxTable", GetListOfToDo());
        }
        // GET: ToDoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDo toDo = db.toDos.Find(id);
            if(toDo == null)
            {
                return HttpNotFound();
            }

            string currentUserId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.FirstOrDefault(x => x.Id == currentUserId);
            toDo.user = currentUser;
            if(toDo.user != currentUser)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(toDo);
        }

        // POST: ToDoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,title,description,reminder,isDone")] ToDo toDo)
        {
            if(ModelState.IsValid)
            {
                db.Entry(toDo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(toDo);
        }

        [HttpPost]

        public ActionResult AjaxEdit(int? id, bool value)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDo toDo = db.toDos.Find(id);
            if(toDo == null)
            {
                return HttpNotFound();
            }
            else
            {
                toDo.isDone = value;
                db.Entry(toDo).State = EntityState.Modified;
                db.SaveChanges();
            }

            return PartialView("_TodoAjaxTable", GetListOfToDo());
        }


        // GET: ToDoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDo toDo = db.toDos.Find(id);
            if(toDo == null)
            {
                return HttpNotFound();
            }
            return View(toDo);
        }

        // POST: ToDoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ToDo toDo = db.toDos.Find(id);
            db.toDos.Remove(toDo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if(disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        //this should be in a scheduller
        public ActionResult SendEmail()
        {

            return View();
        }

        [HttpPost]
        public ActionResult SendEmail(ToDo obj)
        {
            string currentUserId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.FirstOrDefault(x => x.Id == currentUserId);
            var reminder = db.toDos.ToList().Where(x => x.user == currentUser && x.isDone == false).OrderByDescending(x => x.id);
            foreach(var item in reminder)
            {
                TimeSpan hours = DateTime.Now.Subtract(Convert.ToDateTime(item.reminder));
                if(hours.Hours > 12)
                {
                    try
                    {
                        //Configuring webMail class to send emails  
                        //gmail smtp server  
                        WebMail.SmtpServer = "smtp.gmail.com";
                        //gmail port to send emails  
                        WebMail.SmtpPort = 587;
                        WebMail.SmtpUseDefaultCredentials = true;
                        //sending emails with secure protocol  
                        WebMail.EnableSsl = true;
                        //EmailId used to send emails from application  
                        WebMail.UserName = "thepen0411@gmail.com";
                        WebMail.Password = "";

                        //Sender email address.  
                        WebMail.From = "thepen0411@gmail.com";

                        //Send email  
                        WebMail.Send(to: currentUser.Email, subject: obj.title, body: obj.description, isBodyHtml: true);
                        ViewBag.Status = "Email Sent Successfully.";
                    }
                    catch(Exception ex)
                    {
                        ViewBag.Status = "Problem while sending email, Please check details.";
                        Elmah.ErrorSignal.FromCurrentContext().Raise(ex);

                    }

                }
            }

            return View();

        }
    }
}

ToDoListApp/Views/ToDoes/Create.cshtml
@model ToDoListApp.Models.ToDo

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.12.4.min.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ToDo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.reminder, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.reminder, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                @Html.ValidationMessageFor(model => model.reminder, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isDone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isDone)
                    @Html.ValidationMessageFor(model => model.isDone, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">
    $(function () {
        // This will make every element with the class "date-picker" into a DatePicker element
        $('.date-picker').datepicker();
    })
</script>
}

ToDoListApp/Views/ToDoes/Delete.cshtml
@model ToDoListApp.Models.ToDo

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ToDo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.reminder)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.reminder)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isDone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isDone)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ToDoListApp/Views/ToDoes/Details.cshtml
@model ToDoListApp.Models.ToDo

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ToDo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.reminder)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.reminder)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isDone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isDone)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ToDoListApp/Views/ToDoes/Edit.cshtml
@model ToDoListApp.Models.ToDo

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ToDo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.reminder, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.reminder, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                @Html.ValidationMessageFor(model => model.reminder, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isDone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isDone)
                    @Html.ValidationMessageFor(model => model.isDone, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ToDoListApp/Views/ToDoes/Index.cshtml
@model ToDoListApp.Models.ToDo

@{
    ViewBag.Title = "Index";
}
<h4 class="btn btn-info btn-block">Your List</h4>
<br />
<div id="dynamictable">

</div>
<div id="dynamicajaxform">
    @using(Ajax.BeginForm("CreateAjaxForm", "ToDoes", new AjaxOptions
    {
        InsertionMode = InsertionMode.Replace,
        HttpMethod = "POST",
        UpdateTargetId = "dynamictable"
    }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4 class="btn btn-info btn-block">Create New Task</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
              
                <div class="col-md-10">
                    @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" , @placeholder = "Title" } })
                    @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
             
                <div class="col-md-10">
                    @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control", @placeholder = "Description" } })
                    @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
               
                <div class="col-md-10">
                    @Html.EditorFor(model => model.reminder, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                    @Html.ValidationMessageFor(model => model.reminder, "", new { @class = "text-danger" })
                </div>
            </div>

            @*<div class="form-group">
                @Html.LabelFor(model => model.isDone, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.isDone)
                        @Html.ValidationMessageFor(model => model.isDone, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>*@

            <div class="form-group">
                <div class="col-md-10">
                    <input type="submit" value="Create" class="btn btn-primary btn-block" />
                </div>
            </div>
        </div>
    }
</div>
@section Scripts{

    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/CustomScripts/addDynamicTable.js"></script>
    @Scripts.Render("~/bundles/jqueryval")
}

ToDoListApp/Views/ToDoes/_TodoAjaxTable.cshtml
@model IEnumerable<ToDoListApp.Models.ToDo>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.reminder)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.isDone)
        </th>
        <th></th>
    </tr>

    @foreach(var item in Model)
    {
        <tr>
            <td>
               
                @Html.DisplayFor(modelItem => item.title)
            </td>
            <td>
                @if(!item.isDone)
                {
                    @Html.DisplayFor(modelItem => item.description)
                }
                else
                {
                    <div class="IsdoneClass">@Html.DisplayFor(modelItem => item.description)</div>
                   
                }
               
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.reminder)
            </td>
            <td>
                @Html.CheckBoxFor(modelItem => item.isDone, new { id = item.id, @class = "checkboxes" })
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                @*@Html.ActionLink("Details", "Details", new { id = item.id }) |*@
                @Html.ActionLink("Delete", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>

<script src="~/CustomScripts/handleIsdoneEvent.js"></script>